### ISSUE TITLE
Access presenter blurb

### ISSUE THREAD

**Issue by russel** [abingham/accu-2017-elm-app#27]
There doesn't seem to be a way of accessing presenter blurb. At least using Chrome on Debian Sid the names are not links.

**Comment by abingham** [comment]
Right, I'm not pulling that over yet. It's a good idea, though, so I'll see if I can get it in before the conference.

**Comment by abingham** [comment]
@russel I've started work on showing presenter bios in the [`presenter-bio` branch](https://github.com/abingham/accu-2017-elm-app/tree/presenter-bio). It's crude right now, but you can test it out if you use the dev server (i.e. use `nf start` to run everything).

This is going to require changes to the ACCU website since it currently doesn't serve up bio information. I've got [a branch doing this on my fork](https://github.com/abingham/ACCUConf_Website/commit/92cfede8acb4fd1de1d723a43125de1cafaa5d79) that you might look at. Essentially, where we used to "embed" presenter information in the proposals, the presenters are now shipped over as part of a separate request.

So, think about what you might want in terms of displaying presenter info. I'm think about creating "card" similar to what we've got for proposals. The presenters name would be at the top, maybe a company name in the subheader if that's available, with a list of their proposals in the body. The "action" block could include twitter buttons or something. Give it some thought.

**Comment by abingham** [comment]
This has been fixed since about 35fb7e2645fd08395384f6c1100a2eeb87b0c674
