### ISSUE TITLE
No link specific pointer

### ISSUE THREAD

**Issue by russel** [abingham/accu-2017-elm-app#28]
Using Chrome on Debian Sid, I see the arrow pointer when not over text and the I pointer over text, there is no change to the hand pointer over links. The lack of feedback makes it difficult to know when hovering over a link that can be clicked. The consequence is that it is not totally clear that the name of a session in the schedule is a link to the blurb.

**Comment by abingham** [comment]
Yeah, I noticed this myself earlier today. I'll see what I can do. Those aren't "links" per se, just elements that respond to click events. If I can't change the cursor, something like adding elevation or shading on mouse-over might do the trick.

**Comment by abingham** [comment]
To do elevation on mouse over, see [this example](http://debois.github.io/elm-mdl/#cards). Basically, we need to store the raise state in the model and use the right elevation based on that state.

**Comment by abingham** [comment]
The cards now get extra elevation when they're moused over. This is intended to make them appear more obviously clickable.

@russel Does this seem like a reasonable solution to you?

**Comment by russel** [comment]
I think it would, just add that bit of affordance. Interestingly, with a touch screen touching any part of the card goes to the detail, which works nicely. Also I note that I get the hand icon hovering over the day on a card different from the I pointer hovering over all the other sensitive bits, and usual pointer elsewhere.

**Comment by abingham** [comment]
> the hand icon hovering over the day on a card different from the I pointer hovering over all the other sensitive bits, and usual pointer elsewhere.

Yes, it's perhaps a questionable decision (and easy to remove), but I thought it might be nice to be able to click on the day and see that day. I'll also do something similar for presenters. So the day and presenter will be normal links with the associated pointer, while the rest of the card will be clickable without being a proper link. 

If this turns out to be confusing, then we could make the title clickable while keeping the card in general unclickable. This stuff is all pretty easy to experiment with.

So for now I'll close this out.
